Update Jenkins

diff --git a/Jenkins b/Jenkins
--- a/Jenkins
+++ b/Jenkins
@@ -2,42 +2,43 @@ pipeline {
     agent any
 
     environment {
-        // Correct way to bind AWS credentials in a declarative pipeline
-        AWS_ACCESS_KEY_ID     = credentials('aws-s3-backup-creds')
-        AWS_SECRET_ACCESS_KEY = credentials('aws-s3-backup-creds')
-        S3_BUCKET             = 's3://jenkinsbackupsuvam'
+        S3_BUCKET = 's3://jenkinsbackupsuvam'
     }
 
     stages {
-        // We removed the manual 'Checkout' stage because Jenkins does it automatically
-        
+
         stage('Archive & Compress') {
             steps {
                 echo "Packaging files from workspace..."
-                // This archives the code Jenkins just pulled from Git
-                sh 'tar -czf jenkins-project.tar.gz .'
+                sh '''
+                tar --exclude='.git' --exclude='*.tar.gz' \
+                -czf jenkins-project.tar.gz .
+                '''
             }
         }
 
         stage('Upload to AWS S3') {
             steps {
-                echo "Pushing artifact to AWS..."
-                // AWS CLI automatically uses the AWS_ACCESS_KEY_ID env variables
-                sh "aws s3 cp jenkins-project.tar.gz ${S3_BUCKET}/backups2/"
+                echo "Uploading artifact to S3..."
+                withCredentials([[$class: 'AmazonWebServicesCredentialsBinding',
+                  credentialsId: 'aws-s3-backup-creds']]) {
+
+                    sh "aws s3 cp jenkins-project.tar.gz ${S3_BUCKET}/backups2/"
+                }
             }
         }
     }
 
     post {
         always {
-            echo "Cleaning up workspace..."
-            sh 'rm -f *.tar.gz'
+            echo "Cleaning workspace..."
+            sh '[ -f jenkins-project.tar.gz ] && rm jenkins-project.tar.gz || true'
         }
         success {
-            echo "Deployment to S3 successful!"
+            echo "Upload successful!"
         }
         failure {
-            echo "Build failed. Please check the 'hhttps' typo in your SCM settings or Jenkinsfile."
+            echo "Pipeline failed. Check logs."
         }
     }
 }
